name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      npm_config_yes: true
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install EAS CLI
        run: npm install -g eas-cli
        
      - name: Login to Expo
        run: npx eas-cli login --token ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        working-directory: frontend
        run: |
          rm -f yarn.lock
          npm install --legacy-peer-deps
          
      - name: Build APK
        working-directory: frontend
        run: npx eas-cli build --platform android --profile preview --non-interactive
